name: Compile Project
on:
  workflow_dispatch:
  push:
    branches:
      - development
      - main
      - release/**

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
            
jobs:
  CompileAndBuild:
    name: Compile to 4DZ
    runs-on: macOS-latest
    permissions: write-all    
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Restore Cache for tool4d app
        id: restore-tool4d-cache
        uses: actions/cache@v4.0.2
        env:
          cache-name: tool4d-cache
        with:
          path:  ./tool4d.app
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.restore-tool4d-cache.outputs.cache-hit != 'true' }}
        name: Download latest tool4d release and expand
        continue-on-error: true
        timeout-minutes: 15
        run: |
          curl https://resources-download.4d.com/release/20.x/20.3/latest/mac/tool4d_mac_x86.tar.xz -o tool4d.tar.xz -sL
          tar xzf tool4d.tar.xz
        
      - name: Compile and Build 4DZ Package for ${{ github.ref }}
        run: |
          ./tool4d.app/Contents/MacOS/tool4d  --project=${{ github.workspace }}/Project/Contacts.4DProject --user-param="compileproject" --skip-onstartup --dataless --startup-method=GHPipeline_EntryPoint_P 

      - uses: actions/upload-artifact@v4.3.1
        name: Upload Artifacts
        with:
          name: Compile-Results
          path: |
            Compiled Database/
            Project/Contacts_ci-compileproject_results.json
          
      - name: "Pass or Fail"
        run: |
          [[ $(jq .command.success Project/Contacts_ci-compileproject_results.json) == true ]] || { exit 1; }
        
  release-content:
    name: 'Create Project Release'
    runs-on: ubuntu-latest
    needs: [ CompileAndBuild ]
    # if: startsWith(github.ref, 'refs/tags/')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:      
      - name: 'Download Build Artifacts'
        uses: actions/download-artifact@v4.1.4

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: Compile-Results
          filename: 'Contacts-R${{ github.run_number }}.zip'

      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          release_notes_file: RELEASE_NOTES.md

      - name: 'Create Project Release'
        uses: softprops/action-gh-release@v2.0.4
        with:
          generate_release_notes: true
          body_path: RELEASE_NOTES.md
          files: 'Contacts-R${{ github.run_number }}.zip'
          tag_name: v${{ github.run_number }}
          name: Release V${{ github.run_number }}
