name: Compile Project
on:
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'
  push:
    branches:
      - development
      - main
      - release/**

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
            
jobs:
  CompileAndBuild:
    name: Compile to 4DZ
    runs-on: macOS-latest
    permissions: write-all    
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Restore Cache for tool4d app
        id: restore-tool4d-cache
        uses: actions/cache@v4.0.2
        env:
          cache-name: tool4d-cache
        with:
          path:  ./tool4d.app
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.restore-tool4d-cache.outputs.cache-hit != 'true' }}
        name: Download latest tool4d release and expand
        continue-on-error: true
        timeout-minutes: 15
        run: |
          curl https://resources-download.4d.com/release/20.x/20.3/latest/mac/tool4d_mac_x86.tar.xz -o tool4d.tar.xz -sL
          tar xzf tool4d.tar.xz
        
      - name: Compile and Build 4DZ Package for ${{ github.ref }}
        run: |
          ./tool4d.app/Contents/MacOS/tool4d  --project=${{ github.workspace }}/Project/Contacts.4DProject --user-param="compileproject" --skip-onstartup --dataless --startup-method=GHPipeline_EntryPoint_P 

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: "${{ github.workspace }}/.github/configure-notes.json"
          outputFile: ${{ github.workspace }}/CHANGELOG.md
          fromTag: "v2.1.0"
          toTag: "v110"

      - name: Verify Files
        run: |
          ls -la
          cat CHANGELOG.md
            
      - uses: actions/upload-artifact@v4.3.1
        name: Upload Artifacts
        with:
          name: Compile-Results
          path: |
            Compiled Database/
            Project/Contacts_ci-compileproject_results.json
            CHANGELOG.md
          
      - name: "Pass or Fail"
        run: |
          [[ $(jq .command.success Project/Contacts_ci-compileproject_results.json) == true ]] || { exit 1; }
        
  release-content:
    name: 'Create Project Release'
    runs-on: ubuntu-latest
    needs: [ CompileAndBuild ]
    # if: startsWith(github.ref, 'refs/tags/')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      ACTIONS_STEP_DEBUG: true
    steps:      
      - name: 'Download Build Artifacts'
        uses: actions/download-artifact@v4.1.4

      - name: Verify Files
        run: |
          ls -la Compile-Results/

      # - name: Extract release notes
      #   id: extract-release-notes
      #   uses: ffurrer2/extract-release-notes@v2
      #   with:
      #     changelog_file: ${{ github.workspace }}/Compile-Results/CHANGELOG.md 
      #     release_notes_file: ${{ github.workspace }}/Compile-Results/RELEASE_NOTES.md

      - name: Create Release Notes
        id: release-notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAME: RELEASE_NOTES
          USE_MILESTONE_TITLE: "true"
      
      - name: Verify Files
        run: |
          ls -la
          ls -la Compile-Results/
          cat ${{ steps.release-notes.outputs }}
          cat Compile-Results/CHANGELOG.md
          cat Compile-Results/RELEASE_NOTES.md
          
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Contacts-R${{ github.run_number }}.zip'
          path: | 
            Compile-Results

      - name: 'Create Project Release'
        uses: softprops/action-gh-release@v2.0.4
        with:
          generate_release_notes: true
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: 'Contacts-R${{ github.run_number }}.zip'
          tag_name: v1.${{ github.run_number }}
          name: Release V1.${{ github.run_number }}
