name: Merged PRs
on:
    pull_request:
      types:
        - closed
  
jobs:
  merged:
    name: PR Merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
  