name: Approved PRs
on:
  pull_request_review:
    types: 
      - submitted
  
jobs:
  approved:
    name: PR Approved
    if: github.event.review.state == 'APPROVED'
    runs-on: macOS-latest
    steps:
      - run: echo "This PR was approved and can be merged"