# Trigger the workflow on milestone events
name: Milestone Closure
on:
  workflow_dispatch:
  milestone:
    types: [closed]

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: release@users.noreply.github.com
        ACTION_NAME: release
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        MD_FOLDER: temp_release_notes
        OWNER: skoona
        REPO_NAME: 4DExplorer
        SKIP_MD: README.md
