name: Check Syntax
on:
  pull_request:
    branches:
      - development
    paths: 
      - 'Project/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  CheckSyntax:
    name: Check Syntax on Windows
    runs-on: windows-2019
    permissions: write-all    
    steps:
      - uses: actions/checkout@v3
      - name: "Download latest tool4d release and expand"
        timeout-minutes: 15
        run: |
          curl https://resources-download.4d.com/release/20.x/20.3/101192/win/tool4d_win.tar.xz -o tool4d.tar.xz           
          C:\Program Files\Git\usr\bin\tar.exe -xvJf tool4d.tar.xz -C tool4d

      - name: "Run Project syntax check"
        timeout-minutes: 15
        run: |
          ./tool4d/tool4d.exe --project=${{ github.workspace }}/Project/Contacts.4DProject --user-param="checksyntax" --skip-onstartup --create-data --startup-method=GH_SyntaxCheck_P 

      - uses: actions/upload-artifact@v3
        name: Upload Artifacts
        with:
          name: Syntax Results
          path: Project/Contacts_ci-checksyntax_results.json
          
      - name: "Pass or Fail"
        run: |
          [[ $(jq .command.success Project/Contacts_ci-checksyntax_results.json) == true ]] || { exit 1; }

          

