name: Check Syntax
on:
  pull_request:
    branches:
      - development
    paths: 
      - 'Project/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  CheckSyntax:
    name: Check Syntax on ${{ github.ref_name }}
    runs-on: macOS-latest
    permissions: write-all    
    steps:
      - name: Restore Cache for tool4d app
        id: restore-tool4d-cache
        uses: actions/cache@v3
        env:
          cache-name: tool4d-cache
        with:
          path:  ./tool4d.app
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - if: ${{ steps.restore-tool4d-cache.outputs.cache-hit != 'true' }}
        name:  Download latest tool4d release and expand
        continue-on-error: true
        timeout-minutes: 15
        run: |
          curl https://resources-download.4d.com/release/20.x/20.3/latest/mac/tool4d_mac_x86.tar.xz -o tool4d.tar.xz -sL
          tar xzf tool4d.tar.xz

      - if: ${{ steps.restore-tool4d-cache.outputs.cache-hit != 'true' }}          
        name: Create Cache tool4d app
        id: create-tool4d-cache
        uses: actions/cache@v3
        env:
          cache-name: tool4d-cache
        with:
          path:  ./tool4d.app
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/checkout@v3
      - name: "Run Project syntax check"
        timeout-minutes: 15
        run: |
          ./tool4d.app/Contents/MacOS/tool4d --project=${{ github.workspace }}/Project/Contacts.4DProject --user-param="checksyntax" --skip-onstartup --dataless --startup-method=GHPipeline_EntryPoint_P 

      - uses: actions/upload-artifact@v4.3.1
        name: Upload Artifacts
        with:
          name: Syntax Results
          path: Project/Contacts_ci-checksyntax_results.json
          
      - name: "Pass or Fail"
        run: |
          [[ $(jq .command.success Project/Contacts_ci-checksyntax_results.json) == true ]] || { exit 1; }

          