name: Tool4D Caching
on:
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  CacheTool4D:
    name: Check Syntax on ${{ github.ref_name }}
    runs-on: macOS-latest
    permissions: write-all    
    steps:
      - name: Restore Cache for tool4d app
        id: restore-tool4d-cache
        uses: actions/cache@v3
        env:
          cache-name: tool4d-cache
        with:
          path:  ./tool4d.app
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - if: ${{ steps.restore-tool4d-cache.outputs.cache-hit != 'true' }}
        name:  Download latest tool4d release and expand
        continue-on-error: true
        timeout-minutes: 15
        run: |
          curl https://resources-download.4d.com/release/20.x/20.3/latest/mac/tool4d_mac_x86.tar.xz -o tool4d.tar.xz -sL
          tar xzf tool4d.tar.xz
